pipeline{
    agent any
    stages{
        stage("Build Application"){
            steps{
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
                // sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post{
                success{
                    echo "Now archiving the artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage("Deploy in staging environment"){
            build job: 'tomcat-deploy-stage'
        }
    }
}